config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  get 'index', to: 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true 
  validates :cuteness, presence: true 
  validates :softness, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.xml { render :xml => @kittens }
      format.json { render :json => @kittens }
    end   
  end 

  def new
    @kitten = Kitten.new
  end 

  def create
    @kitten = Kitten.new(kitten_params) 
    if @kitten.save
      flash[:success] = "You created a new kitten"
      redirect_to kitten_url(@kitten)
    else 
      flash.now[:danger] = "You fucked up"
      render :new
    end 
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end 

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html 
      format.xml { render xml: @kitten }
      format.json { render json: @kitten }
    end 
  end  

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "updated details"
      redirect_to root_url
    else 
      flash.now[:danger] = "You fucked up"
      render :edit 
    end   
  end 

  def destroy
    @kitten = Kitten.find(params[:id]).destroy
    flash[:success] = "deleted kitten"
    redirect_to root_url
  end

  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_errors.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
  <div class="alert alert-danger">
  The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
   <li> <%= msg %> </li>
   <% end %>
   </ul>
  </div>
<% end %>

app/views/kittens/_form.html.erb
<section>
<%= form_for(@kitten, url: yield(:path)) do |f| %>
  <%= render 'errors', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :cuteness %>
  <%= f.number_field :cuteness %>

  <%= f.label :softness %>
  <%= f.number_field :softness %>

  <%= f.submit yield(:button_text) %>
  <% end %>
</section>  




  

app/views/kittens/edit.html.erb
<%= provide(:button_text, "Edit Kitten") %>
<%= provide(:path, kitten_path(@kitten)) %>
<h1> Edit Page </h1>
<%= render 'form' %>

app/views/kittens/index.html.erb
<%= link_to "New", new_kitten_path %>
<% @kittens.each do |kitten| %><br>
<%= link_to "Edit", edit_kitten_path(kitten) %>
  Name:<%= kitten.name %>
  Age:<%= kitten.age %>
  Cuteness:<%= kitten.cuteness %>
  Softness:<%= kitten.softness %>
  <br> 
<% end %>

app/views/kittens/new.html.erb
<%= provide(:button_text, "Create a Kitten") %>
<%= provide(:path, kittens_path) %>
<h1> Create Page </h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
   </div>
  </body>
</html>